#Makefile MUPEN64GC for Gamecube with glN64 Graphics

CC		=powerpc-gekko-gcc
CXX		=powerpc-gekko-g++
AS		=powerpc-gekko-as

CFLAGS  = -g -O2 -Wall $(MACHDEP) $(INCLUDE) \
	  -DCPU_SHUTDOWN -DSPC700_SHUTDOWN -DVAR_CYCLES -DSOUND \
	  -DNOASM -DNGC -DNOASM -DPIXEL_FORMAT=RGB565  \
	  -fno-exceptions -Wno-unused-parameter -pipe \
	  -DUSE_GUI -DHW_DOL -DGLN64_GX -DSHOW_DEBUG -DTHREADED_AUDIO \
	  -DUSE_TLB_CACHE -DUSE_RECOMP_CACHE -DPPC_DYNAREC
#	  -DDEBUGON  -DGLN64_SDLOG -DUSE_EXPANSION

MACHDEP	= -DGEKKO -mcpu=750 -meabi -mhard-float 
LDFLAGS	= $(MACHDEP) -mogc -Wl,-Map,$(notdir $@).map -Wl,--cref

INCLUDE = -I$(DEVKITPRO)/libogc/include -I$(DEVKITPRO)/libfat/libogc/include 
LIBPATHS = -L$(DEVKITPRO)/libogc/lib/cube -L$(DEVKITPRO)/libfat/libogc/lib/cube

CXXFLAGS	=$(CFLAGS)

OBJ		=main/rom_gc.o \
		main/main_gc-menu.o \
		main/gc_dvd.o \
		main/ROM-Cache.o \
		main/timers.o \
		fileBrowser/fileBrowser-DVD.o \
		fileBrowser/fileBrowser-CARD.o \
		fileBrowser/fileBrowser-libfat.o \
		fileBrowser/fileBrowser.o \
		gui/menu.o \
		gui/menuFileBrowser.o \
		gui/background_tex.o \
		gui/gui_GX-menu.o \
		gui/GUI.o \
		gui/DEBUG.o \
		gui/TEXT.o \
		gui/font.o \
		r4300/r4300.o \
		r4300/cop0.o \
		r4300/special.o \
		r4300/regimm.o \
		r4300/exception.o \
		r4300/Invalid_Code.o \
		r4300/Recomp-Cache-Heap.o \
		gc_memory/ARAM.o \
		gc_memory/tlb.o \
		gc_memory/TLB-Cache-hash.o \
		gc_memory/memory.o \
		gc_memory/dma.o \
		r4300/interupt.o \
		r4300/cop1.o \
		r4300/tlb.o \
		r4300/cop1_w.o \
		r4300/cop1_s.o \
		r4300/cop1_d.o \
		r4300/recomp.o \
		gc_memory/pif.o \
		r4300/bc.o \
		r4300/cop1_l.o \
		r4300/pure_interp.o \
		r4300/compare_core.o \
		gc_memory/flashram.o \
		main/md5.o \
		main/savestates_gc.o \
		r4300/profile.o \
		main/adler32.o
		
OBJ_PPC		=r4300/ppc/MIPS-to-PPC.o \
		r4300/ppc/Recompile.o \
		r4300/ppc/Wrappers.o \
		r4300/ppc/Register-Cache.o

OBJ_INPUT	=gc_input/main.o \
		gc_input/controller-GC.o

OBJ_RSPHLE	=rsp_hle-ppc/main.o \
		rsp_hle-ppc/jpeg.o \
		rsp_hle-ppc/ucode3.o \
		rsp_hle-ppc/ucode2.o \
		rsp_hle-ppc/ucode1.o

OBJ_AUDIO	=gc_audio/main.o

OBJ_GLN64_GX	=glN64_GX/glN64.o \
		glN64_GX/Config_linux.o \
		glN64_GX/OpenGL.o \
		glN64_GX/N64.o \
		glN64_GX/RSP.o \
		glN64_GX/VI.o \
		glN64_GX/Textures.o \
		glN64_GX/FrameBuffer.o \
		glN64_GX/Combiner.o \
		glN64_GX/gDP.o \
		glN64_GX/gSP.o \
		glN64_GX/GBI.o \
		glN64_GX/DepthBuffer.o \
		glN64_GX/CRC.o \
		glN64_GX/2xSAI.o \
		glN64_GX/TEV_combiner.o \
		glN64_GX/RDP.o \
		glN64_GX/F3D.o \
		glN64_GX/F3DEX.o \
		glN64_GX/F3DEX2.o \
		glN64_GX/L3D.o \
		glN64_GX/L3DEX.o \
		glN64_GX/L3DEX2.o \
		glN64_GX/S2DEX.o \
		glN64_GX/S2DEX2.o \
		glN64_GX/F3DPD.o \
		glN64_GX/F3DDKR.o \
		glN64_GX/F3DWRUS.o

LIB		=	-lm -lfat -logc -lz

ifeq ($(strip mupen64_GX_gfx/main.cpp),)
	export LD	:=	$(CC)
else
	export LD	:=	$(CXX)
endif

all:	mupen64gc-glN64.elf

r4300/interupt.o:	r4300/interupt.c
				@echo $<
				@$(CC) $(CFLAGS) -c -o $@ $<

gui/background_tex.o:		gui/background_tex.s
				@echo $<
				@$(CC) $(CFLAGS) -c -o $@ $<

gc_input/main.o:		gc_input/input.c
				@echo $<
				@$(CC) $(CFLAGS) -c -o $@ $<

rsp_hle-ppc/main.o:			rsp_hle-ppc/main.c
				@echo $<
				@$(CC) $(CFLAGS) -c -o $@ $<

gc_audio/main.o:		gc_audio/audio.c
				@echo $<
				@$(CC) $(CFLAGS) -c -o $@ $<

glN64_GX/glN64.o:			glN64_GX/glN64.cpp
				@echo $<
				@$(CXX) $(CFLAGS) -DMAINDEF -D__LINUX__ -D__GX__ -c -o $@ $<
#				$(CXX) $(CFLAGS) -DMAINDEF -D__LINUX__ -DX86_ASM `sdl-config --cflags` -c -o $@ $<

glN64_GX/Config_linux.o:		glN64_GX/Config_linux.cpp
				@echo $<
				@$(CXX) $(CFLAGS) $(GTK_FLAGS) -D__LINUX__ -D__GX__ -c -o $@ $<

glN64_GX/OpenGL.o:			glN64_GX/OpenGL.cpp
				@echo $<
				@$(CXX) $(CFLAGS) -D__LINUX__ -D__GX__ -c -o $@ $<

glN64_GX/N64.o:			glN64_GX/N64.cpp
				@echo $<
				@$(CXX) $(CFLAGS) -D__LINUX__ -D__GX__ -c -o $@ $<

glN64_GX/RSP.o:			glN64_GX/RSP.cpp
				@echo $<
				@$(CXX) $(CFLAGS) -D__LINUX__ -D__GX__ -c -o $@ $<

glN64_GX/VI.o:			glN64_GX/VI.cpp
				@echo $<
				@$(CXX) $(CFLAGS) -D__LINUX__ -D__GX__ -c -o $@ $<

glN64_GX/Textures.o:		glN64_GX/Textures.cpp
				@echo $<
				@$(CXX) $(CFLAGS) -D__LINUX__ -D__GX__ -c -o $@ $<

glN64_GX/FrameBuffer.o:		glN64_GX/FrameBuffer.cpp
				@echo $<
				@$(CXX) $(CFLAGS) -D__LINUX__ -D__GX__ -c -o $@ $<

glN64_GX/Combiner.o:		glN64_GX/Combiner.cpp
				@echo $<
				@$(CXX) $(CFLAGS) -D__LINUX__ -D__GX__ -c -o $@ $<

glN64_GX/gDP.o:			glN64_GX/gDP.cpp
				@echo $<
				@$(CXX) $(CFLAGS) -D__LINUX__ -D__GX__ -c -o $@ $<

glN64_GX/gSP.o:			glN64_GX/gSP.cpp
				@echo $<
				@$(CXX) $(CFLAGS) -D__LINUX__ -D__GX__ -c -o $@ $<

glN64_GX/GBI.o:			glN64_GX/GBI.cpp
				@echo $<
				@$(CXX) $(CFLAGS) -D__LINUX__ -D__GX__ -c -o $@ $<

glN64_GX/DepthBuffer.o:			glN64_GX/DepthBuffer.cpp
				@echo $<
				@$(CXX) $(CFLAGS) -D__LINUX__ -D__GX__ -c -o $@ $<

glN64_GX/CRC.o:			glN64_GX/CRC.cpp
				@echo $<
				@$(CXX) $(CFLAGS) -D__LINUX__ -D__GX__ -c -o $@ $<

glN64_GX/2xSAI.o:			glN64_GX/2xSAI.cpp
				@echo $<
				@$(CXX) $(CFLAGS) -D__LINUX__ -D__GX__ -c -o $@ $<

glN64_GX/TEV_combiner.o: glN64_GX/TEV_combiner.cpp
				@echo $<
				@$(CXX) $(CFLAGS) -D__LINUX__ -D__GX__ -c -o $@ $<

glN64_GX/RDP.o:			glN64_GX/RDP.cpp
				@echo $<
				@$(CXX) $(CFLAGS) -D__LINUX__ -D__GX__ -c -o $@ $<

glN64_GX/F3D.o:			glN64_GX/F3D.cpp
				@echo $<
				@$(CXX) $(CFLAGS) -D__LINUX__ -D__GX__ -c -o $@ $<

glN64_GX/F3DEX.o:		glN64_GX/F3DEX.cpp
				@echo $<
				@$(CXX) $(CFLAGS) -D__LINUX__ -D__GX__ -c -o $@ $<

glN64_GX/F3DEX2.o:			glN64_GX/F3DEX2.cpp
				@echo $<
				@$(CXX) $(CFLAGS) -D__LINUX__ -D__GX__ -c -o $@ $<

glN64_GX/L3D.o:			glN64_GX/L3D.cpp
				@echo $<
				@$(CXX) $(CFLAGS) -D__LINUX__ -D__GX__ -c -o $@ $<

glN64_GX/L3DEX.o:			glN64_GX/L3DEX.cpp
				@echo $<
				@$(CXX) $(CFLAGS) -D__LINUX__ -D__GX__ -c -o $@ $<

glN64_GX/L3DEX2.o:			glN64_GX/L3DEX2.cpp
				@echo $<
				@$(CXX) $(CFLAGS) -D__LINUX__ -D__GX__ -c -o $@ $<

glN64_GX/S2DEX.o:			glN64_GX/S2DEX.cpp
				@echo $<
				@$(CXX) $(CFLAGS) -D__LINUX__ -D__GX__ -c -o $@ $<

glN64_GX/S2DEX2.o:			glN64_GX/S2DEX2.cpp
				@echo $<
				@$(CXX) $(CFLAGS) -D__LINUX__ -D__GX__ -c -o $@ $<

glN64_GX/F3DPD.o:			glN64_GX/F3DPD.cpp
				@echo $<
				@$(CXX) $(CFLAGS) -D__LINUX__ -D__GX__ -c -o $@ $<

glN64_GX/F3DDKR.o:			glN64_GX/F3DDKR.cpp
				@echo $<
				@$(CXX) $(CFLAGS) -D__LINUX__ -D__GX__ -c -o $@ $<

glN64_GX/F3DWRUS.o:		glN64_GX/F3DWRUS.cpp
				@echo $<
				@$(CXX) $(CFLAGS) -D__LINUX__ -D__GX__ -c -o $@ $<

#Default rule to build the rest of the C files
%.o: %.c
	@echo $<
	@$(CC) $(CFLAGS) -c -o $@ $<
	

mupen64gc-glN64.elf:	$(OBJ) $(OBJ_INPUT) $(OBJ_GLN64_GX) $(OBJ_AUDIO) $(OBJ_RSPHLE) main/main_gc-menu.o $(OBJ_PPC)
						@echo linking ... $(notdir $@)
						@$(LD) $^ $(LDFLAGS) $(LIBPATHS) $(LIB) -Wl -o $@
						@echo linking ... mupen64gc-glN64.dol
						@powerpc-gekko-objcopy -O binary $@ mupen64gc-glN64.dol
	
clean:
	@echo Deleting previously compiled files..
	@find . -name '*.o' -print0 | xargs -0r rm -f

